version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comics-backend
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/comicsdb
    depends_on:
      - mongo
    networks:
      - comics-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"

  mongo:
    image: mongo:7
    container_name: comics-db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - comics-net

networks:
  comics-net:

volumes:
  mongo_data:
