version: "3.9"

services:
  backend:
    build: ./backend
    container_name: comics-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/comicsdb
    depends_on:
      - mongo
    networks:
      - comics-net

  frontend:
    build: ./frontend
    container_name: comics-frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - comics-net

  mongo:
    image: mongo:7
    container_name: comics-db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - comics-net

networks:
  comics-net:

volumes:
  mongo_data:
